---
version: '3'

networks:
  synapse:
    external: true
  caddy:
    external: true

# https://github.com/matrix-org/synapse/blob/e550ab17adc8dd3c48daf7fedcd09418a73f524b/contrib/docker/docker-compose.yml
services:
  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    container_name: synapse
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./app:/data
      # - ./media:/data/media
    depends_on:
      - synapse-postgres
    networks:
      - caddy
      - synapse

  synapse-postgres:
    image: postgres:15-alpine
    container_name: synapse-postgres
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      # Lang stuff is required or Synapse crashes
      - POSTGRES_INITDB_ARGS=-E UTF8
      - LANG=en_US.utf8
      - LC_COLLATE=C
      - LC_CTYPE=C
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - synapse

  whatsapp:
    container_name: whatsapp
    image: dock.mau.dev/mautrix/whatsapp
    restart: unless-stopped
    volumes:
      - ./app/bridges/whatsapp:/data
    depends_on:
      - synapse-postgres
    networks:
      - synapse
      - caddy

  element:
    image: vectorim/element-web:latest
    container_name: element
    restart: unless-stopped
    #ports:
    #  - 88:80
    volumes:
      - ./app/element.json:/app/config.json
    depends_on:
      - synapse
    networks:
      - caddy

  openai:
    # https://github.com/matrixgpt/matrix-chatgpt-bot/
    image: ghcr.io/matrixgpt/matrix-chatgpt-bot:latest
    container_name: openai
    volumes:
      - ./app/bridges/openai:/storage
    env_file:
      - ./.env
    networks:
      - caddy
      - synapse

#    #environment:
#      #- OPENAI_API_KEY=${OPENAI_API_KEY}
#      #- MATRIX_HOMESERVER_URL=${MATRIX_HOMESERVER_URL}
#      #- MATRIX_BOT_USERNAME=${MATRIX_BOT_USERNAME}
#      #- MATRIX_BOT_PASSWORD=${MATRIX_BOT_PASSWORD}
#      #- MATRIX_ACCESS_TOKEN=${MATRIX_ACCESS_TOKEN}
#      #- MATRIX_WHITELIST=${MATRIX_WHITELIST}
#      #- MATRIX_BLACKLIST=${MATRIX_BLACKLIST}
#      #- MATRIX_ENCRYPTION=true
#      #- MATRIX_DEFAULT_PREFIX=!openai
#      #- MATRIX_DEFAULT_PREFIX_REPLY=false
#      #- MATRIX_AUTOJOIN=true  # bot autojoins rooms when invited
#      #- MATRIX_ENCRYPTION=true
#      #- MATRIX_THREADS=true
#      #- MATRIX_PREFIX_DM=false
#      #- MATRIX_RICH_TEXT=true
#      #- CHATGPT_CONTEXT=thread
#      #- CHATGPT_API_MODEL=gpt-3.5-turbo

  synapse-admin:
    image: awesometechnologies/synapse-admin:latest
    container_name: synapse-admin
    restart: unless-stopped
    #ports:
    #  use this if you don't have a reverse proxy
    #  - 33334:80
    environment:
      - REACT_APP_SERVER="https://haume.nz"
    depends_on:
      - synapse
    networks:
      - caddy
      - synapse

#  facebook:
#    container_name: facebook
#    image: dock.mau.dev/mautrix/facebook
#    restart: unless-stopped
#    volumes:
#      - ./app/bridges/facebook:/data
#    networks:
#      - synapse
#
#  signal:
#    container_name: signal
#    image: dock.mau.dev/mautrix/signal
#    restart: unless-stopped
#    volumes:
#      - ./app/bridges/signal:/data
#      - ./app/bridges/signald:/signald
#    depends_on:
#      - signald
#    networks:
#      - synapse
#
#  signald:
#    container_name: signald
#    image: docker.io/signald/signald
#    restart: unless-stopped
#    volumes:
#      - ./app/bridges/signald:/signald
#    networks:
#      - synapse


  # matrix-registration-bot:
    # image: moanos/matrix-registration-bot:latest
    # environment:
      # LOGGING_LEVEL: DEBUG
      # BOT_SERVER: "https://haume.nz"
      # BOT_USERNAME: "registration-bot"
      # BOT_PASSWORD: "sanctuary-propeller-grill"
      # API_BASE_URL: "https://haume.nz"
      # #API_TOKEN: "syt_xxxxxxxxxxxxxxxxxxxxxxxx"
    # networks:
      # - synapse
