version: '3'

networks:
  caddy:
    external: true

services:
  vaultwarden:
    #image: vaultwarden/server:latest
    image: quay.io/vaultwarden/server:alpine
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      #- LOG_LEVEL=debug
    volumes:
      - ./app:/data
    networks:
      - caddy

