version: "3.0"

networks:
  caddy:
    external: true

services:
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    restart: unless-stopped
    volumes:
      - ./app/:/var/opt/memos
    #ports:
    #  - 5230:5230
    networks:
      - caddy
